// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: ingestor.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsageInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	ProductSku    string                 `protobuf:"bytes,2,opt,name=product_sku,json=productSku,proto3" json:"product_sku,omitempty"`
	UsedAmount    int32                  `protobuf:"varint,3,opt,name=used_amount,json=usedAmount,proto3" json:"used_amount,omitempty"`
	UseUnity      string                 `protobuf:"bytes,4,opt,name=use_unity,json=useUnity,proto3" json:"use_unity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageInfoRequest) Reset() {
	*x = UsageInfoRequest{}
	mi := &file_ingestor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageInfoRequest) ProtoMessage() {}

func (x *UsageInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageInfoRequest.ProtoReflect.Descriptor instead.
func (*UsageInfoRequest) Descriptor() ([]byte, []int) {
	return file_ingestor_proto_rawDescGZIP(), []int{0}
}

func (x *UsageInfoRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *UsageInfoRequest) GetProductSku() string {
	if x != nil {
		return x.ProductSku
	}
	return ""
}

func (x *UsageInfoRequest) GetUsedAmount() int32 {
	if x != nil {
		return x.UsedAmount
	}
	return 0
}

func (x *UsageInfoRequest) GetUseUnity() string {
	if x != nil {
		return x.UseUnity
	}
	return ""
}

var File_ingestor_proto protoreflect.FileDescriptor

const file_ingestor_proto_rawDesc = "" +
	"\n" +
	"\x0eingestor.proto\x12\vyourpackage\x1a\x1bgoogle/protobuf/empty.proto\"\x89\x01\n" +
	"\x10UsageInfoRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1f\n" +
	"\vproduct_sku\x18\x02 \x01(\tR\n" +
	"productSku\x12\x1f\n" +
	"\vused_amount\x18\x03 \x01(\x05R\n" +
	"usedAmount\x12\x1b\n" +
	"\tuse_unity\x18\x04 \x01(\tR\buseUnity2P\n" +
	"\fUsageService\x12@\n" +
	"\aConsume\x12\x1d.yourpackage.UsageInfoRequest\x1a\x16.google.protobuf.EmptyB-Z+github.com/gabriwl165/commerce-system/protob\x06proto3"

var (
	file_ingestor_proto_rawDescOnce sync.Once
	file_ingestor_proto_rawDescData []byte
)

func file_ingestor_proto_rawDescGZIP() []byte {
	file_ingestor_proto_rawDescOnce.Do(func() {
		file_ingestor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestor_proto_rawDesc), len(file_ingestor_proto_rawDesc)))
	})
	return file_ingestor_proto_rawDescData
}

var file_ingestor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ingestor_proto_goTypes = []any{
	(*UsageInfoRequest)(nil), // 0: yourpackage.UsageInfoRequest
	(*empty.Empty)(nil),      // 1: google.protobuf.Empty
}
var file_ingestor_proto_depIdxs = []int32{
	0, // 0: yourpackage.UsageService.Consume:input_type -> yourpackage.UsageInfoRequest
	1, // 1: yourpackage.UsageService.Consume:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ingestor_proto_init() }
func file_ingestor_proto_init() {
	if File_ingestor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestor_proto_rawDesc), len(file_ingestor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestor_proto_goTypes,
		DependencyIndexes: file_ingestor_proto_depIdxs,
		MessageInfos:      file_ingestor_proto_msgTypes,
	}.Build()
	File_ingestor_proto = out.File
	file_ingestor_proto_goTypes = nil
	file_ingestor_proto_depIdxs = nil
}
